  let index = 0;
  export const data = [
    { key: index++, section: true, label: 'Country' },
   
    {key: index++, "code3": "AFG", label: "Afghanistan"},
    {key: index++, "code3": "ALB", label: "Albania"},
    {key: index++, "code3": "DZA", label: "Algeria"},
    {key: index++, "code3": "ASM", label: "American Samoa"},
    {key: index++, "code3": "AND", label: "Andorra"},
    {key: index++, "code3": "AGO", label: "Angola"},
    {key: index++, "code3": "AIA", label: "Anguilla",               },
    {key: index++, "code3": "ATA", label: "Antarctica",             },
    {key: index++, "code3": "ATG", label: "Antigua and Barbuda",    },
    {key: index++, "code3": "ARG", label: "Argentina",              },
    {key: index++, "code3": "ARM", label: "Armenia",                },
    {key: index++, "code3": "ABW", label: "Aruba",                  },
    {key: index++, "code3": "AUS", label: "Australia",              },
    {key: index++, "code3": "AUT", label: "Austria",                },
    {key: index++, "code3": "AZE", label: "Azerbaijan",             },
    {key: index++, "code3": "BHS", label: "Bahamas (the)",          },
    {key: index++, "code3": "BHR", label: "Bahrain",                },
    {key: index++, "code3": "BGD", label: "Bangladesh",             },
    {key: index++, "code3": "BRB", label: "Barbados",               },
    {key: index++, "code3": "BLR", label: "Belarus",                },
    {key: index++, "code3": "BEL", label: "Belgium",                },
    {key: index++, "code3": "BLZ", label: "Belize",                 },
    {key: index++, "code3": "BEN", label: "Benin",                  },
    {key: index++, "code3": "BMU", label: "Bermuda",                },
    {key: index++, "code3": "BTN", label: "Bhutan",                 },
    {key: index++, "code3": "BOL", label: "Bolivia (Plurinational State of)",},
    {key: index++, "code3": "BES", label: "Bonaire, Sint Eustatius and Saba",},
    {key: index++, "code3": "BIH", label: "Bosnia and Herzegovina",          },
    {key: index++, "code3": "BWA", label: "Botswana",                        },
    {key: index++, "code3": "BVT", label: "Bouvet Island",                   },
    {key: index++, "code3": "BRA", label: "Brazil",                          },
    {key: index++, "code3": "IOT", label: "British Indian Ocean Territory (the)",},
    {key: index++, "code3": "BRN", label: "Brunei Darussalam",                  },
    {key: index++, "code3": "BGR", label: "Bulgaria",                           },
    {key: index++, "code3": "BFA", label: "Burkina Faso",                       },
    {key: index++, "code3": "BDI", label: "Burundi",                            },
    {key: index++, "code3": "CPV", label: "Cabo Verde",                         },
    {key: index++, "code3": "KHM", label: "Cambodia",                           },
    {key: index++, "code3": "CMR", label: "Cameroon",                           },
    {key: index++, "code3": "CAN", label: "Canada",                             },
    {key: index++, "code3": "CYM", label: "Cayman Islands (the)",               },
    {key: index++, "code3": "CAF", label: "Central African Republic (the)",     },
    {key: index++, "code3": "TCD", label: "Chad",  },
    {key: index++, "code3": "CHL", label: "Chile", },
    {key: index++, "code3": "CHN", label: "China", },
    {key: index++, "code3": "CXR", label: "Christmas Island",              },
    {key: index++, "code3": "CCK", label: "Cocos (Keeling) Islands (the)",},
    {key: index++, "code3": "COL", label: "Colombia",                      },
    {key: index++, "code3": "COM", label: "Comoros (the)",                 },
    {key: index++, "code3": "COD", label: "Congo (the Democratic Republic of the)"},
    {key: index++, "code3": "COG", label: "Congo (the)",                    },
    {key: index++, "code3": "COK", label: "Cook Islands (the)",             },
    {key: index++, "code3": "CRI", label: "Costa Rica",                     },
    {key: index++, "code3": "HRV", label: "Croatia",                        },
    {key: index++, "code3": "CUB", label: "Cuba",                           },
    {key: index++, "code3": "CUW", label: "Curaçao",                        },
    {key: index++, "code3": "CYP", label: "Cyprus",                         },
    {key: index++, "code3": "CZE", label: "Czechia",                        },
    {key: index++, "code3": "CIV", label: "Côte d'Ivoire",                  },
    {key: index++, "code3": "DNK", label: "Denmark",                        },
    {key: index++, "code3": "DJI", label: "Djibouti",                       },
    {key: index++, "code3": "DMA", label: "Dominica",                       },
    {key: index++, "code3": "DOM", label: "Dominican Republic (the)",       },
    {key: index++, "code3": "ECU", label: "Ecuador",                        },
    {key: index++, "code3": "EGY", label: "Egypt",                          },
    {key: index++, "code3": "SLV", label: "El Salvador",                    },
    {key: index++, "code3": "GNQ", label: "Equatorial Guinea",              },
    {key: index++, "code3": "ERI", label: "Eritrea",                        },
    {key: index++, "code3": "EST", label: "Estonia",                        },
    {key: index++, "code3": "SWZ", label: "Eswatini",                       },
    {key: index++, "code3": "ETH", label: "Ethiopia",                       },
    {key: index++, "code3": "FLK", label: "Falkland Islands (the) [Malvinas]"},
    {key: index++, "code3": "FRO", label: "Faroe Islands (the)",           },
    {key: index++, "code3": "FJI", label: "Fiji",                          },
    {key: index++, "code3": "FIN", label: "Finland",                       },
    {key: index++, "code3": "FRA", label: "France",                        },
    {key: index++, "code3": "GUF", label: "French Guiana",                 },
    {key: index++, "code3": "PYF", label: "French Polynesia",              },
    {key: index++, "code3": "ATF", label: "French Southern Territories (the)", },
    {key: index++, "code3": "GAB", label: "Gabon",                       },
    {key: index++, "code3": "GMB", label: "Gambia (the)",                },
    {key: index++, "code3": "GEO", label: "Georgia",                     },
    {key: index++, "code3": "DEU", label: "Germany",                     },
    {key: index++, "code3": "GHA", label: "Ghana",                       },
    {key: index++, "code3": "GIB", label: "Gibraltar",                   },
    {key: index++, "code3": "GRC", label: "Greece",                      },
    {key: index++, "code3": "GRL", label: "Greenland",                   },
    {key: index++, "code3": "GRD", label: "Grenada"},
    {key: index++, "code3": "GLP", label: "Guadeloupe"},
    {key: index++, "code3": "GUM", label: "Guam"},
    {key: index++, "code3": "GTM", label: "Guatemala"},
    {key: index++, "code3": "GGY", label: "Guernsey"},
    {key: index++, "code3": "GIN", label: "Guinea"},
    {key: index++, "code3": "GNB", label: "Guinea-Bissau"},
    {key: index++, "code3": "GUY", label: "Guyana"},
    {key: index++, "code3": "HTI", label: "Haiti",},
    {key: index++, "code3": "HMD", label: "Heard Island and McDonald Islands"},
    {key: index++, "code3": "VAT", label: "Holy See (the)"},
    {key: index++, "code3": "HND", label: "Honduras"},
    {key: index++, "code3": "HKG", label: "Hong Kong"},
    {key: index++, "code3": "HUN", label: "Hungary"},
    {key: index++, "code3": "ISL", label: "Iceland"},
    {key: index++, "code3": "IND", label: "India"},
    {key: index++, "code3": "IDN", label: "Indonesia"},
    {key: index++, "code3": "IRN", label: "Iran (Islamic Republic of)"},
    {key: index++, "code3": "IRQ", label: "Iraq", },
    {key: index++, "code3": "IRL", label: "Ireland",},
    {key: index++, "code3": "IMN", label: "Isle of Man"},
    {key: index++, "code3": "ISR", label: "Israel", },
    {key: index++, "code3": "ITA", label: "Italy", },
    {key: index++, "code3": "JAM", label: "Jamaica"},
    {key: index++, "code3": "JPN", label: "Japan",},
    {key: index++, "code3": "JEY", label: "Jersey", },
    {key: index++, "code3": "JOR", label: "Jordan",},
    {key: index++, "code3": "KAZ", label: "Kazakhstan",},
    {key: index++, "code3": "KEN", label: "Kenya",     },
    {key: index++, "code3": "KIR", label: "Kiribati",  },
    {key: index++, "code3": "PRK", label: "Korea (the Democratic People's Republic of)"},
    {key: index++, "code3": "KOR", label: "Korea (the Republic of)"},
    {key: index++, "code3": "KWT", label: "Kuwait",     },
    {key: index++, "code3": "KGZ", label: "Kyrgyzstan", },
    {key: index++, "code3": "LAO", label: "Lao People's Democratic Republic (the)", },
    {key: index++, "code3": "LVA", label: "Latvia", },
    {key: index++, "code3": "LBN", label: "Lebanon",},
    {key: index++, "code3": "LSO", label: "Lesotho",},
    {key: index++, "code3": "LBR", label: "Liberia",},
    {key: index++, "code3": "LBY", label: "Libya",  },
    {key: index++, "code3": "LIE", label: "Liechtenstein",},
    {key: index++, "code3": "LTU", label: "Lithuania",    },
    {key: index++, "code3": "LUX", label: "Luxembourg",   },
    {key: index++, "code3": "MAC", label: "Macao",        },
    {key: index++, "code3": "MDG", label: "Madagascar",   },
    {key: index++, "code3": "MWI", label: "Malawi",       },
    {key: index++, "code3": "MYS", label: "Malaysia",     },
    {key: index++, "code3": "MDV", label: "Maldives",     },
    {key: index++, "code3": "MLI", label: "Mali",         },
    {key: index++, "code3": "MLT", label: "Malta",        },
    {key: index++, "code3": "MHL", label: "Marshall Islands (the)",},
    {key: index++, "code3": "MTQ", label: "Martinique",  },
    {key: index++, "code3": "MRT", label: "Mauritania",  },
    {key: index++, "code3": "MUS", label: "Mauritius",   },
    {key: index++, "code3": "MYT", label: "Mayotte",     },
    {key: index++, "code3": "MEX", label: "Mexico",      },
    {key: index++, "code3": "FSM", label: "Micronesia (Federated States of)",},
    {key: index++, "code3": "MDA", label: "Moldova (the Republic of)"},
    {key: index++, "code3": "MCO", label: "Monaco",     },
    {key: index++, "code3": "MNG", label: "Mongolia",   },
    {key: index++, "code3": "MNE", label: "Montenegro", },
    {key: index++, "code3": "MSR", label: "Montserrat", },
    {key: index++, "code3": "MAR", label: "Morocco",    },
    {key: index++, "code3": "MOZ", label: "Mozambique", },
    {key: index++, "code3": "MMR", label: "Myanmar",    },
    {key: index++, "code3": "NAM", label: "Namibia",    },
    {key: index++, "code3": "NRU", label: "Nauru",      },
    {key: index++, "code3": "NPL", label: "Nepal",      },
    {key: index++, "code3": "NLD", label: "Netherlands (the)",},
    {key: index++, "code3": "NCL", label: "New Caledonia",    },
    {key: index++, "code3": "NZL", label: "New Zealand",      },
    {key: index++, "code3": "NIC", label: "Nicaragua",        },
    {key: index++, "code3": "NER", label: "Niger (the)",      },
    {key: index++, "code3": "NGA", label: "Nigeria",          },
    {key: index++, "code3": "NIU", label: "Niue",             },
    {key: index++, "code3": "NFK", label: "Norfolk Island",   },
    {key: index++, "code3": "MNP", label: "Northern Mariana Islands (the)"},
    {key: index++, "code3": "NOR", label: "Norway",     },
    {key: index++, "code3": "OMN", label: "Oman",       },
    {key: index++, "code3": "PAK", label: "Pakistan",   },
    {key: index++, "code3": "PLW", label: "Palau",      },
    {key: index++, "code3": "PSE", label: "Palestine, State of",},
    {key: index++, "code3": "PAN", label: "Panama",          },
    {key: index++, "code3": "PNG", label: "Papua New Guinea",},
    {key: index++, "code3": "PRY", label: "Paraguay",        },
    {key: index++, "code3": "PER", label: "Peru",            },
    {key: index++, "code3": "PHL", label: "Philippines (the)"},
    {key: index++, "code3": "PCN", label: "Pitcairn",        },
    {key: index++, "code3": "POL", label: "Poland",          },
    {key: index++, "code3": "PRT", label: "Portugal",        },
    {key: index++, "code3": "PRI", label: "Puerto Rico",     },
    {key: index++, "code3": "QAT", label: "Qatar",           },
    {key: index++, "code3": "MKD", label: "Republic of North Macedonia"},
    {key: index++, "code3": "ROU", label: "Romania",        },
    {key: index++, "code3": "RUS", label: "Russian Federation (the)", },
    {key: index++, "code3": "RWA", label: "Rwanda",           },
    {key: index++, "code3": "REU", label: "Réunion",          },
    {key: index++, "code3": "BLM", label: "Saint Barthélemy", },
    {key: index++, "code3": "SHN", label: "Saint Helena, Ascension and Tristan da Cunha"},
    {key: index++, "code3": "KNA", label: "Saint Kitts and Nevis",      },
    {key: index++, "code3": "LCA", label: "Saint Lucia",                },
    {key: index++, "code3": "MAF", label: "Saint Martin (French part)", },
    {key: index++, "code3": "SPM", label: "Saint Pierre and Miquelon",  },
    {key: index++, "code3": "VCT", label: "Saint Vincent and the Grenadines",},
    {key: index++, "code3": "WSM", label: "Samoa",                           },
    {key: index++, "code3": "SMR", label: "San Marino",                      },
    {key: index++, "code3": "STP", label: "Sao Tome and Principe",           },
    {key: index++, "code3": "SAU", label: "Saudi Arabia",                    },
    {key: index++, "code3": "SEN", label: "Senegal", },
    {key: index++, "code3": "SRB", label: "Serbia"},
    {key: index++, "code3": "SYC", label: "Seychelles"},
    {key: index++, "code3": "SLE", label: "Sierra Leone"},
    {key: index++, "code3": "SGP", label: "Singapore", },
    {key: index++, "code3": "SXM", label: "Sint Maarten (Dutch part)"},
    {key: index++, "code3": "SVK", label: "Slovakia", },
    {key: index++, "code3": "SVN", label: "Slovenia"},
    {key: index++, "code3": "SLB", label: "Solomon Islander"},
    {key: index++, "code3": "SOM", label: "Somalia"},
    {key: index++, "code3": "ZAF", label: "South Africa"},
    {key: index++, "code3": "SGS", label: "South Georgia outh Sandwich Islands"},
    {key: index++, "code3": "SSD", label: "South Sudan", },
    {key: index++, "code3": "ESP", label: "Spain"},
    {key: index++, "code3": "LKA", label: "Sri Lanka"},
    {key: index++, "code3": "SDN", label: "Sudan (the)"},
    {key: index++, "code3": "SUR", label: "Suriname"},
    {key: index++, "code3": "SJM", label: "Svalbard and Jan Mayen"},
    {key: index++, "code3": "SWE", label: "Sweden"},
    {key: index++, "code3": "CHE", label: "Switzerland"},
    {key: index++, "code3": "SYR", label: "Syrian Arab Republic"},
    {key: index++, "code3": "TWN", label: "Taiwan"},
    {key: index++, "code3": "TJK", label: "Tajikistan"},
    {key: index++, "code3": "TZA", label: "Tanzania, United Republic of"},
    {key: index++, "code3": "THA", label: "Thailand"},
    {key: index++, "code3": "TLS", label: "Timor-Leste"},
    {key: index++, "code3": "TGO", label: "Togo"},
    {key: index++, "code3": "TKL", label: "Tokelau"},
    {key: index++, "code3": "TON", label: "Tonga"},
    {key: index++, "code3": "TTO", label: "Trinidad and Tobago"},
    {key: index++, "code3": "TUN", label: "Tunisia"},
    {key: index++, "code3": "TUR", label: "Turkey"},
    {key: index++, "code3": "TKM", label: "Turkmenistan"},
    {key: index++, "code3": "TCA", label: "Turks and Caicos Islands (the)"},
    {key: index++, "code3": "TUV", label: "Tuvalu"},
    {key: index++, "code3": "UGA", label: "Uganda"},
    {key: index++, "code3": "UKR", label: "Ukraine"},
    {key: index++, "code3": "ARE", label: "United Arab Emirates (the)"},
    {key: index++, "code3": "GBR", label: "United Kingdom of Great Britain and Northern Ireland (the)"},
    {key: index++, "code3": "UMI", label: "United States Minor Outlying Islands (the)"},
    {key: index++, "code3": "USA", label: "United States of America (the)"},
    {key: index++, "code3": "URY", label: "Uruguay"},
    {key: index++, "code3": "UZB", label: "Uzbekistan"},
    {key: index++, "code3": "VUT", label: "Vanuatu",},
    {key: index++, "code3": "VEN", label: "Venezuela (Bolivarian Republic of)"},
    {key: index++, "code3": "VNM", label: "Viet Nam",},
    {key: index++, "code3": "VGB", label: "Virgin Islands (British)"},
    {key: index++, "code3": "VIR", label: "Virgin Islands (U.S.)"},
    {key: index++, "code3": "WLF", label: "Wallis and Futuna"},
    {key: index++, "code3": "ESH", label: "Western Sahara"},
    {key: index++, "code3": "YEM", label: "Yemen"},
    {key: index++, "code3": "ZMB", label: "Zambia"},
    {key: index++, "code3": "ZWE", label: "Zimbabwe"},
    {key: index++, "code3": "ALA", label: "Åland Islands"},
];