export const GENERAL_ERROR = 'GENERAL_ERROR';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const INVALID_USER = 'INVALID_USER';
export const FACEBOOK_SDK = 'FACEBOOK_SDK';
export const FACEBOOK_SDK_CANCEL = 'FACEBOOK_SDK_CANCEL';
export const GOOGLE_SIGN_IN_CANCELLED = 'GOOGLE_SIGN_IN_CANCELLED';
export const GOOGLE_SIGN_IN_PROGRESS = 'GOOGLE_SIGN_IN_PROGRESS';
export const GOOGLE_PLAY_SERVICES_NOT_AVAILABLE =
  'GOOGLE_PLAY_SERVICES_NOT_AVAILABLE';
export const AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED';
export const CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND';
export const INVALID_CODE = 'INVALID_CODE';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const INVALID_PHONE_OR_EMAIL = 'INVALID_PHONE_OR_EMAIL';
export const DEEP_STREAM_ERROR = "DEEP_STREAM_ERROR";
